---
vpc_id: "${vpc_id}"
vpn_id: "${vpn_id}"
tunnel1_address: "${tunnel1_address}"
tunnel1_preshared_key: "${tunnel1_preshared_key}"
tunnel1_vgw_inside_address: "${tunnel1_vgw_inside_address}"
tunnel1_cgw_inside_address: "${tunnel1_cgw_inside_address}"
tunnel1_bgp_asn: "${tunnel1_bgp_asn}"
bgp_asn: "${bgp_asn}"
tunnel2_address: "${tunnel2_address}"
tunnel2_preshared_key: "${tunnel2_preshared_key}"
tunnel2_vgw_inside_address: "${tunnel2_vgw_inside_address}"
tunnel2_cgw_inside_address: "${tunnel2_cgw_inside_address}"
tunnel2_bgp_asn: "${tunnel2_bgp_asn}"